### ISSUE TITLE
Orchil converts colour hex to a quartet

### ISSUE THREAD

**Issue by AnthonyHJ** [ChatTheatre/orchil#7] opened 2020-09-13 12:41 UTC
Orchil requires its own theme for Castle Marrach (and I assume other games) as it seemingly truncates all of the colour values from #rrggbb to #rgba with unfortunate results.

**Comment by noahgibbs** [comment] 2020-09-22 12:59
Heya. I think I'm misunderstanding what you're writing here -- I'm just getting up to speed with Orchil. Can you show me an example of the problem?

**Comment by AnthonyHJ** [comment] 2020-09-22 13:37
It's possible that Castle Marrach is using an outdated version of the code, but let's take the @who output using a theme called Retro... (I am using Chrome's inspector to check the colours)

In another client, the text colour is set to 237, 148, 48 (#ED9430) or a kind of orange.
In Orchil, that same text comes out as 238, 221, 153, 0.267 (#EEDD9944) because it's truncating the original hex.

**Comment by noahgibbs** [comment] 2020-09-22 14:03
That makes sense. I'm using Orchil on The Gables, but I can't tell if it has the same sort of themes. I'll see if I can reproduce the problem there...

**Comment by kurzon-marrach** [comment] 2020-10-15 15:46
I originally noticed this bug back before we released Orchil in Castle Marrach, but wasn't able to get it resolved at the time. I did some extensive testing in both Marrach and Allegory to confirm the bug was related to the client itself, and not one specific theatre.

**TEST 1: Checking my current saved theme**

To experiment, I logged a character into Allegory using the Orchil client. I could see that some color tags were appearing right away, so I used @profile to see what color theme was set in my body: it was set to the theme 'ironclaw' which was peculiar as this was a brand new character and I'd never set a profile theme in him before. This led me to believe that I was actually inheriting the theme 'ironclaw' from the UrChatter.

To confirm this, I manually unset my theme using **_@profile theme none_**. The game gave confirmation that my theme was removed, so I used **_@profile_** to again check my theme - it was still displaying as 'ironclaw' even though I had just unset it.

This almost certainly means that what they've done over at Allegory, is that somewhere in the UrChatter parent chain they've manually set all chatters to inherit the theme 'ironclaw'. In addition to that, they've written a script that executes on chatter login to delete a character's saved color theme preferences to ensure they don't override the preferred theme they set in the Ur.

**TEST 2: Testing Skotos themes on Allegory**

To confirm the next part of my theory I started playing with my color theme on the Allegory side. A handful of the color themes available in Castle Marrach are actually Skotos-wide and accessible in every Skotos theatre that uses the same clients as us. For this experiment I used a theme that's available in every Skotos theatre: 'eruption'. Orchil doesn't have a dropdown menu to select different themes like older clients do so it's not as obvious over there that you can do this, but they're still accessible. In this case, I entered: **_@profile theme eruption_** to switch to the desired theme. Doing this manually set my theme back to 'eruption' over 'ironclaw' even though Allegory's login script deletes this information when I log back in.

The results more or less confirmed what I thought. 

Here's a picture of what eruption should (and does) look like using ZEALOTRY on MARRACH:
http://images.marrach.com/testing/theme_eruption_zealotry.png

Nothing fancy, generally 'volcanic' reds and oranges on a dark background. It looks like this on every client from Zealotry to Flash to even Alice way back in the day.

Here's what that same theme looks like in ORCHIL on Marrach
http://images.marrach.com/testing/theme_eruption_orchil_marrach.png

As you can see, our oranges and reds are now bright green after switching to Orchil.

Now a third example, the same theme, again in ORCHIL but this time on ALLEGORY
http://images.marrach.com/testing/theme_eruption_orchil_allegory.png

Again, bright green instead of the deep oranges 'eruption' is supposed to display, regardless of the theater being played. The issue seems to be client side with Orchil (and only Orchil).

**OTHER ISSUE: Text Background**

While we're here, it's worth mentioning one other color related error - whatever background color you set in your profile, Orchil seems not to recognize it whatsoever. The only way to change your background color is to use the clientpref settings, ie: **_clientpref theme dark_**. The above screencaps were taken setting my Orchil theme to 'dark', but had I not done so, those images would all have the white (default) background despite that they are designed to have dark backgrounds in their server-side color settings.

**Comment by kurzon-marrach** [comment] 2020-11-18 00:55
Are we having any luck on this?

**Comment by noahgibbs** [comment] 2021-02-25 10:14
Found the problem. Orchil has a method called stripQuotes that it's using on all Alice attributes (color, xch_cmd, title, class) that just cuts off extra characters. There are probably problems with the other attributes too, but color shows the problem very clearly.

I'll submit a PR to Orchil for this. It will fix the "colours look wrong" error, but not the "Orchil doesn't set a background colour" error - I don't know how that background colour gets communicated to the client but I'm not seeing it in any of the Alice messages (the ones starting with SKOOT) so I don't think I can just passively parse the right answer and drop it into place - presumably I need to query it somehow, and presumably Zealotry already does that.

(Quick check to the Zealotry code...) Oh wow. Huh. So Mozilla had a weird competitor to COM and CORBA called XPCOM, and that's what the old client was written in. Uh. Hrm. And it looks like those preferences are set in the actual browser, so they're stored by Firefox? Huh.

That means I can't query it using Orchil. I could do something similar using browser localstorage, but it wouldn't import the old Zealotry prefs. But I'll think on whether there's an easy way to use localstorage for Orchil preferences. Probably -- localstorage isn't terribly difficult. And that means that getting Orchil to "respect" the background colour preference just means adding an Orchil preference for it, which I don't think currently exists.

**Comment by noahgibbs** [comment] 2021-02-25 10:17
On an unrelated note: do you folks have any idea where/how colours get mapped? For instance a "syntax" atag in the help system gets turned into colour #FFFFFF before it's sent to Orchil or Zealotry, but I have no idea where/how that gets mapped. I *does* clearly get mapped server-side, I just don't know where or if it's configurable. Do you folks know?

**Comment by noahgibbs** [comment] 2021-02-25 10:19
Oh, hey, Orchil already allows you to save clientprefs in localstorage, you just have to actually type "clientprefs save". Silly me. Okay, I'll look at adding a background colour pref.

**Comment by kurzon-marrach** [comment] 2021-02-25 18:58
@noahgibbs Good to see progress on this bug, I had about given up hope!

> On an unrelated note: do you folks have any idea where/how colours get mapped? For instance a "syntax" atag in the help system gets turned into colour #FFFFFF before it's sent to Orchil or Zealotry, but I have no idea where/how that gets mapped. I _does_ clearly get mapped server-side, I just don't know where or if it's configurable. Do you folks know?

Themes get saved server side into the file "TextIF:Themes". They're simply saved as strings of the hexcode, each one to a separate property name. In hindsight this was a bad idea, as the file now has so many properties that you can't open it with Woe without getting an 'insufficient ticks' error, the only ways to view this information is using a property editor such as +kpe which only loads a single property at a time and doesn't bug out, or just doing a `+obstat TextIF:Themes property:*` which will read out all the information directly into your client.

The format it saves them in looks like this:

`colours:themename:tagname = "#hexcode"`

As an example, the color information for the "syntax" tag for the "underbailey" theme would be saved as a property in TextIF:Themes as:

`colours:underbailey:syntax = "#339933"`

**Comment by noahgibbs** [comment] 2021-02-25 19:25
Chris has merged the PR, so you should be able to just copy the latest orchil.js and get the fixes.

Cool! I'll look into the themes, that makes sense. I'll see if there's an easy fix for the insufficient ticks error with WOE. But I'm normally using a client-side text editor for this stuff, so that format should work just fine for me.

**Comment by kurzon-marrach** [comment] 2021-02-25 19:27
> Oh, hey, Orchil already allows you to save clientprefs in localstorage, you just have to actually type "clientprefs save". Silly me. Okay, I'll look at adding a background colour pref.

Background color is saved as "atag tag = background", eg; `colours:villain:background = "#3B3B3B"`. Orchil does not seem to recognize this however, whatever colour it's set to.

Edit: That problem also might not be specific to Orchil. Alice and zealotry had issues where you had to reload the client after editing a theme's background color in order for the change to register (whereas you did not have to do that when changing text, so something is slightly different there).

**Comment by noahgibbs** [comment] 2021-02-25 19:32
Okay. I've made background colour a thing that individual players can set for themselves using the clientpref command, but that's different from the theme colour. I don't see any obvious way to set background colour in Orchil - it may just not do that (yet.) I'll try to figure out how what you wrote above turns into Alice protocol on the wire. I know the colours get pre-translated, but not sure about the background colour.

**Comment by kurzon-marrach** [comment] 2021-02-25 19:57
With the latest update, by default the first time a new player opens Orchil without any saved clientpref settings, is the background color dark or white?

If it's not dark by default, is there a way to do that? A lot of our important information on the default Marrach theme is highlighted in bright atags, so I'd rather first-time logins default to a black background until they customize otherwise.

**Comment by noahgibbs** [comment] 2021-02-25 20:02
That makes sense - we actually just changed it to dark for a different project. I'd be cool with just changing that setting globally. It's not hard to change. If you want to change it for yourself, just search for "light" in orchil.js - it's pretty obvious which one is the default for the "theme" setting, and you can change it to "dark".

**Comment by noahgibbs** [comment] 2021-02-25 20:02
(Also, by default the atags show up in white, which is no good at all on a white background. :-/ )

**Comment by noahgibbs** [comment] 2021-02-25 20:03
Er, at least the syntax atag does.

**Comment by AnthonyHJ** [comment] 2021-02-25 22:18
The background colour is sent in a &lt;body> tag when the theme is loaded. 

For example, &lt;body bgcolor='#404040' text='#F0F0F0' link='#5ABBA1' plink='#5ABBA1'&gt; is returned for the retro theme in Castle Marrach.

**Comment by noahgibbs** [comment] 2021-02-25 22:44
Cool. That sounds easy enough to find. I've looked through some of the Alice protocol, but not that part yet.

**Comment by noahgibbs** [comment] 2021-02-26 07:48
At this point the bug as stated is fixed. I've opened a new issue for the background colour problem and I'm closing this one.

There's also a new issue to default to a dark background, which could be done separately and really easily.

**Comment by noahgibbs** [comment] 2021-02-26 07:49
New background colour bug: https://github.com/ChatTheatre/orchil/issues/19

New dark background bug: https://github.com/ChatTheatre/orchil/issues/20

**Closed as completed by noahgibbs** 2021-02-26 07:48 UTC
